import './globals.css'
import { Silkscreen } from 'next/font/google';
import NextAuthSessionProvider from './providers/sessionProvider'
import Navbar from './components/Navbar';


const silkScreen = Silkscreen({
    subsets: ["latin"],
    style: "normal",
    weight: '400'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={silkScreen.className}>
          <NextAuthSessionProvider>
            <Navbar />
            {children}
          </NextAuthSessionProvider>
      </body>
    </html>
  )
}


